export const SELECTED_GARMENT = "SELECTED_GARMENT";
export const SHOWN_INTRO = "SHOWN_INTRO";
export const SHOW_TUTORIAL = "SHOW_TUTORIAL";
export const SELECTED_FABRIC = "SELECTED_FABRIC";
export const SELECTED_CONTINENT = "SELECTED_CONTINENT";
export const FETCH_MATERIALS_SUCCESS = "FETCH_MATERIALS_SUCCESS";
export const FETCH_MATERIAL_SUCCESS= "FETCH_MATERIAL_SUCCESS";
export const FETCH_SCORES_SUCCESS = "FETCH_SCORES_SUCCESS";
export const FETCH_TIPS_SUCCESS = "FETCH_TIPS_SUCCESS";
export const DROP_DOWN_MENU = "DROP_DOWN_MENU";
export const USER_LOCATION = "USER_LOCATION";
export const WIPE_OUT_SESSION = "WIPE_OUT_SESSION";
export const BEGIN_API_CALL= "BEGIN_API_CALL";

